/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _hashcode;

import _hashcode.models.HorizontalPicture;
import _hashcode.models.Picture;
import _hashcode.models.Slide;
import _hashcode.models.VerticalPicture;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.stream.Collectors;

public class App {
    public static void main(String[] args) {
        ArrayList<Picture> pictures = Reader.read("inputs/c_memorable_moments.txt");
        ArrayList<Slide> slides = makeSlides(pictures);
        Slideshow slideshow =  new Slideshow();
        slides.forEach(slideshow::addSlide);
        System.out.println("slides size: " + slides.size());
        System.out.println("slideshow interestScore:" + slideshow.interestScore());
        Writer.write(slides, "output.txt");
    }

    private static ArrayList<Slide> makeSlides(ArrayList<Picture> pictures) {
        ArrayList<HorizontalPicture> horizontalPictures = new ArrayList<>();
        ArrayList<VerticalPicture> verticalPictures = new ArrayList<>();
        pictures.forEach(picture -> {
            if (picture.ORIENTATION.equals(HorizontalPicture.ORIENTATION)) {
                horizontalPictures.add((HorizontalPicture)picture);
            } else {
                verticalPictures.add((VerticalPicture)picture);
            }
        });

        ArrayList<Slide> slides = new ArrayList<>();
        horizontalPictures.forEach(picture -> slides.add(new Slide(picture)));
        slides.addAll(findVerticalSlides(verticalPictures));
        return slides;
    }

    private static ArrayList<Slide> findVerticalSlides(ArrayList<VerticalPicture> verticalPictures) {
        ArrayList<Slide> slides = new ArrayList<>();
        verticalPictures.sort(Comparator.comparingInt(verticalPicture -> verticalPicture.TAGS.size()));
        for (int i=0; i<verticalPictures.size() / 2; i+=2) {
            slides.add(new Slide(
                verticalPictures.get(i),
                verticalPictures.get((verticalPictures.size() - (i + 1)))
                )
            );
        }
//        slides.forEach(slide -> {
//            System.out.println(slide.tags().size() + " " + slide.PICTURES.get(0) + " " + slide.PICTURES.get(1));
//        });
        return slides;
    }

}
